// Central English copy keeps future translations independent of component layout.
export const copy = {
  brand: "Interphone", tagline: "Your building, within reach.", entrance: "Building entrance",
  apartment: (label: string) => `Apartment ${label}`, optional: "Optional", retry: "Try again", signOut: "Sign out",
  loading: "Getting things ready", loadingDetail: "Connecting to your building…",
  network: "We couldn’t connect. Check your internet connection and try again.",
  stale: "Connection interrupted. Showing the last update; it may be out of date.",
  reconnecting: "Reconnecting… Showing the last update; it may be out of date.",
  status: {
    online: "Controller connected", offline: "Controller offline", unknown: "Connection not confirmed",
    offlineDetail: "Remote entry is unavailable while the entrance controller is offline.",
    onlineDetail: "Ready to receive unlock requests.",
    unknownDetail: "Waiting for a fresh connection update before enabling remote entry.",
  },
  login: {
    eyebrow: "Resident access", title: "Welcome home", detail: "Sign in to receive visitors and manage entry to your building.",
    email: "Email address", password: "Password", show: "Show", hide: "Hide", showPassword: "Show password", hidePassword: "Hide password",
    submit: "Sign in", pending: "Signing in…", help: "Use the account provided by your building administrator.",
    invalid: "The email or password doesn’t match. Check your details and try again.",
    unconfirmed: "Please confirm your email before signing in.", limited: "Too many sign-in attempts. Wait a moment and try again.",
    failed: "We couldn’t sign you in. Please try again.",
  },
  visitor: {
    eyebrow: "Visitor entry", title: "Who are you visiting?", detail: "Choose an apartment. We’ll let the resident know you’re here.",
    apartments: "Choose an apartment", message: "Message to the resident", placeholder: "For example, a delivery or your name",
    count: (n: number) => `${n}/140`, ring: "Ring an apartment", ringApartment: (label: string) => `Ring apartment ${label}`,
    sending: "Sending your ring…", footer: "No account needed. Just ring and wait for a response.",
    empty: "No apartments available", emptyDetail: "This entrance hasn’t been set up yet. Please contact the person you’re visiting.",
    unknown: "Entrance not found", unknownDetail: "This door link isn’t recognised. Check the QR sticker or contact the person you’re visiting.",
    unavailable: "This request is unavailable", unavailableDetail: "We can no longer find this ring. Return to the entrance to choose an apartment.",
    loadFailed: "We couldn’t load this entrance", ringFailed: "Your ring couldn’t be sent. Please try again.",
    limited: "Please wait a minute before ringing again.", offline: "You can still ring the resident, but remote entry is currently unavailable.",
    waiting: "Waiting for a response", waitingDetail: "Your ring has been sent. Keep this page open while the resident responds.",
    answered: "Resident is responding", answeredDetail: "Keep this page open for their entry decision.",
    elapsed: (seconds: number) => `Waiting ${seconds < 60 ? `${seconds}s` : `${Math.floor(seconds / 60)}m ${seconds % 60}s`}`,
    reused: "A recent ring is already waiting for this apartment. We’ll show its response here.",
    chooseAnother: "Choose another apartment", back: "Back to entrance",
  },
  resident: {
    eyebrow: "Resident home", title: "Your entrance", detail: "A little closer to whoever’s at the door.",
    waiting: "No visitors waiting", waitingDetail: "New visitor requests will appear here. You can also unlock the entrance for yourself.",
    incoming: "Visitor at the entrance", incomingDetail: "Someone is waiting for your response.", noMessage: "The visitor didn’t leave a message.",
    unlock: "Unlock entrance", unlocking: "Sending request…", decline: "Decline", declining: "Declining…",
    unlockHelp: "Sends a brief unlock request to the building entrance.", sent: "Unlock request sent",
    sentDetail: "The request has been sent to the entrance controller. Physical opening is not confirmed.",
    queuedOffline: "Unlock request queued, but the controller is offline. Delivery is unconfirmed; an undelivered request expires after 30 seconds.",
    declined: "Entry declined", declineDetail: "The visitor has been notified of your decision.",
    actionFailed: "We couldn’t send your response. Check the connection before trying again.",
    actionUnknown: "Your connection was interrupted. The request may have been sent; check the entrance before trying again.",
    conflict: "This request is no longer available. Refreshing its status…",
    sessionExpired: "Your session has expired. Sign out and sign in again to continue.",
    denied: "This account doesn’t have permission to respond to this request.",
    unassigned: "Your home isn’t linked yet", unassignedDetail: "Ask your building administrator to connect this account to your apartment.",
    loadFailed: "We couldn’t load your home", loadDetail: "Check your connection and try again. Your apartment assignment hasn’t changed.",
    activityFailed: "We couldn’t check for visitors", activityDetail: "Try again to load visitor requests and the entrance connection.",
    activityLoading: "Checking your entrance", activityLoadingDetail: "Looking for visitor requests and a current connection update.",
    ended: "This visit has ended", unavailable: "Visit unavailable", unavailableDetail: "This visit may no longer exist or may not belong to your apartment.",
    returnHome: "Back to your entrance", signOutFailed: "We couldn’t sign you out. Please try again.",
    account: "Your account", accountDetail: "Resident access on this device.",
  },
  notifications: {
    title: "Visitor notifications", detail: "Know when someone rings, even when you’re away from this page.",
    checking: "Checking this device…", available: "Turn on alerts for this device.", enable: "Enable notifications", pending: "Enabling…",
    enabled: "Notifications enabled", enabledDetail: "This device is set up to receive visitor alerts.",
    blocked: "Notifications are blocked", blockedDetail: "Allow notifications for this site in your browser settings, then check again.",
    unsupported: "Notifications unavailable here", unsupportedDetail: "Use a browser that supports web notifications. On iPhone or iPad, add this app to your Home Screen and open it there.",
    unconfigured: "Notifications aren’t set up yet", unconfiguredDetail: "Keep this page open for visitor requests. Your building administrator needs to finish notification setup.",
    failed: "We couldn’t set up notifications. Please try again.", check: "Check again",
  },
  outcomes: {
    ringing: { title: "Waiting for a response", detail: "Waiting for the resident to respond." },
    answered: { title: "Resident is responding", detail: "Keep this page open for their entry decision." },
    unlocked: { title: "Entry approved", detail: "The resident has sent an unlock request. Try the entrance; if it stays locked, contact the resident." },
    denied: { title: "Entry declined", detail: "The resident hasn’t allowed entry. You can contact them directly if needed." },
    expired: { title: "No response this time", detail: "You can try again or choose another apartment." },
    cancelled: { title: "Request cancelled", detail: "This ring has ended. You can start another request when you’re ready." },
  },
} as const;
